%YAML:1.0
robot_length: 5.0

init_x: 0
init_y: 0
goal_x: 4
goal_y: 5

steering_noise: 0.1
distance_noise: 0.03
measurement_noise: 0.3

weight_data: 0.1
weight_smooth: 0.075

p_gain: 2.015625
d_gain: 6.0

